# Site settings
title: About the web team
email: jasonvperrin@gmail.com
description: >
  A description of the history, past and current members of the web team.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://about.fairviewhs.org" # the base hostname & protocol for your site
github_username: fairviewhs
permalink: pretty

defaults:
  -
    scope:
      path: "" # All pages
    values:
      categories: "blog"

# Build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - Gruntfile.js
  - package.json
  - node_modules
